### ISSUE TITLE
[TODO] 아이콘

### ISSUE THREAD

**Issue by Dev-james1112** [Team-Centillion/Main_Page#16]
할일: 

- [ ] [wrapper/nav_wrapper.html](https://github.com/Team-Centillion/Main_Page/blob/main/wrapper/nav_wrapper.html) 에 `<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />` 추가하기
- [ ] [css/style.css](https://github.com/Team-Centillion/Main_Page/blob/main/css/style.css) 에
```
<style>
.material-symbols-rounded {
  font-variation-settings:
  'FILL' 1,
  'wght' 400,
  'GRAD' 0,
  'opsz' 48
}
</style>
``` 
추가하기
- [ ] 다른 아이콘 삽입

담당자: @Paul0309

**Comment by Paul0309** [comment]
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

이 코드
어디다 삽입함?

**Comment by Dev-james1112** [comment]
하이퍼 링크 타고가셈

**Comment by Paul0309** [comment]
코드 중간에 아니면 매 ㄴ위에

**Comment by Dev-james1112** [comment]
맨위

**Comment by Paul0309** [comment]
했다고

**Comment by Dev-james1112** [comment]
@Paul0309  #17

**Comment by Paul0309** [comment]
안됨?

**Comment by Dev-james1112** [comment]
그리고 한 것에는 클릭
![image](https://user-images.githubusercontent.com/79844149/170508739-ce12d2fb-4e2c-4966-97e9-cc24cca42de4.png)

**Comment by Dev-james1112** [comment]
아이콘 클릭해봐

**Comment by Dev-james1112** [comment]
아니 삽입 해봐

**Comment by Paul0309** [comment]
코드가 어떻게 됨

**Comment by Dev-james1112** [comment]
#17
